# Generated by Django 5.0.1 on 2024-01-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='someone', max_length=55),
            preserve_default=False,
        ),
    ]
