# Generated by Django 5.0.1 on 2024-01-18 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_author_user'),
        ('userauth', '0002_remove_journalistprofile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.journalistprofile'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
