# Generated by Django 5.0.1 on 2024-01-18 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_alter_news_author_delete_author'),
        ('userauth', '0002_remove_journalistprofile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalist', to='userauth.journalistprofile'),
        ),
    ]
