# Generated by Django 5.0.1 on 2024-01-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_alter_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='news',
            name='small_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='promotion',
            field=models.ManyToManyField(blank=True, null=True, to='News.promotion'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
