# Generated by Django 5.0.1 on 2024-01-23 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_alter_review_options_alter_review_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='News.promotion'),
        ),
    ]
