# Generated by Django 5.0.1 on 2024-01-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0011_remove_promotion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='category_name_am',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='category_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
