# Generated by Django 5.0.1 on 2024-01-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0012_newscategory_category_name_am_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
