# Generated by Django 5.0.1 on 2024-01-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0016_remove_news_promotion_remove_news_view_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewcount',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
