# Generated by Django 5.0.1 on 2024-01-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_remove_journalistprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalistprofile',
            name='bio',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
