# Generated by Django 5.0.1 on 2024-01-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_userpreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
